const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {test} = require('node:test');

// Python supplies pages generated by the production renderers, with synthetic IDs.
const pages = JSON.parse(fs.readFileSync(0, 'utf8'));

function setup({fetch, opener = false, confirm = true, page = "document"} = {}) {
  const elements = Object.fromEntries(['readerStatus', 'readerPrintBtn', 'readerBackBtn',
    'readerCloseBtn'].map(id => [id, {textContent: '', disabled: false, listeners: {},
    addEventListener(name, callback) { this.listeners[name] = callback; }}]));
  const calls = {requests: [], confirmations: [], focused: 0, closed: 0, timers: []};
  const window = {
    location: {href: '/documents/read?document_id=docref-fixture'},
    opener: opener ? {closed: false, focus: () => { calls.focused++; }} : null,
    close: () => { calls.closed++; },
    setTimeout: (callback, delay) => { calls.timers.push({callback, delay}); },
    confirm: message => { calls.confirmations.push(message); return confirm; },
  };
  const context = vm.createContext({window, document: {getElementById: id => elements[id]},
    fetch: async (url, options) => {
      calls.requests.push({url, options: JSON.parse(JSON.stringify(options))});
      if (!fetch) throw new Error('Unexpected request');
      return fetch(url, options);
    },
  });
  const scripts = [...pages[page].matchAll(/<script>([\s\S]*?)<\/script>/g)];
  assert.equal(scripts.length, 1);
  vm.runInContext(scripts[0][1], context);
  return {elements, calls, window, context};
}

const jsonResponse = data => ({json: async () => data});
const prepared = () => jsonResponse({ok: true, print_job_id: 'fixture-job'});

test('opening the reader does not prepare or send a print job', () => {
  const {elements, calls} = setup();
  assert.deepEqual(calls.requests, []);
  assert.deepEqual(calls.confirmations, []);
  for (const id of ['readerPrintBtn', 'readerBackBtn', 'readerCloseBtn']) {
    assert.equal(typeof elements[id].listeners.click, 'function');
  }
});

for (const page of ['document', 'purchase']) {
test('return focuses the original Cockpit and retains the navigation fallback', () => {
  const {elements, calls, window} = setup({opener: true, page});
  elements.readerBackBtn.listeners.click();
  assert.equal(calls.focused, 1);
  assert.equal(calls.closed, 1);
  assert.equal(calls.timers[0].delay, 350);
  calls.timers[0].callback();
  assert.equal(window.location.href, '/');
  assert.deepEqual(calls.requests, []);
});

test('standalone return navigates to Cockpit without attempting to close it', () => {
  const {elements, calls, window} = setup({page});
  elements.readerBackBtn.listeners.click();
  assert.equal(window.location.href, '/');
  assert.equal(calls.closed, 0);
  assert.deepEqual(calls.requests, []);
});

test('close focuses the opener and provides guidance if closing is blocked', () => {
  const {elements, calls} = setup({opener: true, page});
  elements.readerCloseBtn.listeners.click();
  assert.equal(calls.focused, 1);
  assert.equal(calls.closed, 1);
  assert.equal(calls.timers[0].delay, 300);
  calls.timers[0].callback();
  assert.match(elements.readerStatus.textContent, /Pokud se okno nezavřelo/);
  assert.deepEqual(calls.requests, []);
});

test(`${page}: closed or inaccessible opener cannot block return`, () => {
  for (const closed of [true, false]) {
    const {elements, window, calls} = setup({page, opener: true});
    window.opener.closed = closed;
    window.opener.focus = () => { throw new Error('inaccessible opener'); };
    elements.readerBackBtn.listeners.click();
    for (const timer of calls.timers) timer.callback();
    assert.equal(window.location.href, '/');
    assert.deepEqual(calls.requests, []);
  }
});
}

test('cancelled print prepares one job but does not send it', async () => {
  const {elements, calls} = setup({fetch: prepared, confirm: false});
  await elements.readerPrintBtn.listeners.click();
  assert.deepEqual(calls.requests.map(item => item.url), ['/api/documents/print/prepare']);
  assert.deepEqual(JSON.parse(calls.requests[0].options.body), {document_id: 'docref-fixture'});
  assert.equal(calls.confirmations.length, 1);
  assert.match(elements.readerStatus.textContent, /nebyl odeslán/);
  assert.equal(elements.readerPrintBtn.disabled, false);
});

test('confirmed print uses the exact prepared job and restores the button', async () => {
  let resolve;
  const {elements, calls} = setup({fetch: url => url.endsWith('/prepare')
    ? new Promise(done => { resolve = done; }) : jsonResponse({ok: true, message: 'Fixture printed'})});
  const pending = elements.readerPrintBtn.listeners.click();
  assert.equal(elements.readerPrintBtn.disabled, true);
  resolve(prepared());
  await pending;
  assert.deepEqual(calls.requests.map(item => item.url),
    ['/api/documents/print/prepare', '/api/documents/print/run']);
  assert(calls.requests.every(item => item.options.method === 'POST'
    && item.options.headers['Content-Type'] === 'application/json'));
  assert.deepEqual(JSON.parse(calls.requests[1].options.body), {
    print_job_id: 'fixture-job', confirmation_text: 'Potvrzuji, vytiskni print job fixture-job.',
  });
  assert.equal(elements.readerStatus.textContent, 'Fixture printed');
  assert.equal(elements.readerPrintBtn.disabled, false);
});

test('failed preparation does not ask for confirmation or attempt printing', async () => {
  const {elements, calls} = setup({fetch: () => jsonResponse({ok: false, message: 'Fixture unavailable'})});
  await elements.readerPrintBtn.listeners.click();
  assert.equal(calls.requests.length, 1);
  assert.deepEqual(calls.confirmations, []);
  assert.equal(elements.readerStatus.textContent, 'Fixture unavailable');
  assert.equal(elements.readerPrintBtn.disabled, false);
});

for (const failure of ['network', 'JSON', 'print transport']) {
  test(`${failure} failure is visible and cannot leave printing disabled`, async () => {
    const {elements, calls} = setup({fetch: url => {
      if (failure === 'print transport' && url.endsWith('/prepare')) return prepared();
      if (failure === 'JSON') return {json: async () => { throw new SyntaxError('fixture failure'); }};
      throw new Error('fixture failure');
    }});
    await elements.readerPrintBtn.listeners.click();
    assert.match(elements.readerStatus.textContent, /Chyba tisku:.*fixture failure/);
    assert.equal(elements.readerPrintBtn.disabled, false);
    assert.equal(calls.requests.length, failure === 'print transport' ? 2 : 1);
  });
}
