#!/usr/bin/env python3
"""Build the secret-free source plist for Samantha's urgent reminder Shortcut."""

from __future__ import annotations

import plistlib
import uuid
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "generated_shortcuts" / "Samantha_Dulezite_pripomenuti.xml"
WORKFLOW_NAME = "Samantha – důležité připomenutí"
PLACEHOLDER = "\ufffc"
UUID_NAMESPACE = uuid.UUID("C1BAF92E-7624-45AD-B80A-27F24B6695E0")


def stable_uuid(label: str) -> str:
    return str(uuid.uuid5(UUID_NAMESPACE, label)).upper()


def action(identifier: str, parameters: dict[str, Any] | None = None) -> dict[str, Any]:
    return {
        "WFWorkflowActionIdentifier": identifier,
        "WFWorkflowActionParameters": parameters or {},
    }


def output_reference(output_uuid: str, output_name: str) -> dict[str, str]:
    return {
        "OutputName": output_name,
        "OutputUUID": output_uuid,
        "Type": "ActionOutput",
    }


def token_attachment(output_uuid: str, output_name: str) -> dict[str, Any]:
    return {
        "Value": output_reference(output_uuid, output_name),
        "WFSerializationType": "WFTextTokenAttachment",
    }


def token_string(*parts: str | tuple[str, str]) -> dict[str, Any]:
    text_parts: list[str] = []
    attachments: dict[str, dict[str, str]] = {}
    position = 0
    for part in parts:
        if isinstance(part, str):
            text_parts.append(part)
            position += len(part)
            continue
        output_uuid, output_name = part
        text_parts.append(PLACEHOLDER)
        attachments[f"{{{position}, 1}}"] = output_reference(output_uuid, output_name)
        position += 1
    value: dict[str, Any] = {"string": "".join(text_parts)}
    if attachments:
        value["attachmentsByRange"] = attachments
    return {"Value": value, "WFSerializationType": "WFTextTokenString"}


def current_date_token_string(prefix: str, *, date_format: str) -> dict[str, Any]:
    return {
        "Value": {
            "string": f"{prefix}{PLACEHOLDER}",
            "attachmentsByRange": {
                f"{{{len(prefix)}, 1}}": {
                    "Aggrandizements": [
                        {
                            "Type": "WFDateFormatVariableAggrandizement",
                            "WFDateFormat": date_format,
                            "WFDateFormatStyle": "Custom",
                            "WFISO8601IncludeTime": False,
                        }
                    ],
                    "Type": "CurrentDate",
                }
            },
        },
        "WFSerializationType": "WFTextTokenString",
    }


def dictionary_items(entries: list[tuple[str, dict[str, Any]]]) -> dict[str, Any]:
    items = []
    for key, value in entries:
        items.append(
            {
                "WFItemType": 0,
                "WFKey": token_string(key),
                "WFValue": value,
            }
        )
    return {
        "Value": {"WFDictionaryFieldValueItems": items},
        "WFSerializationType": "WFDictionaryFieldValue",
    }


def condition_input(output_uuid: str, output_name: str) -> dict[str, Any]:
    return {
        "Type": "Variable",
        "Variable": token_attachment(output_uuid, output_name),
    }


def comment(text: str) -> dict[str, Any]:
    return action("is.workflow.actions.comment", {"WFCommentActionText": text})


def show_result(label: str, *parts: str | tuple[str, str]) -> dict[str, Any]:
    return action(
        "is.workflow.actions.showresult",
        {
            "UUID": stable_uuid(label),
            "Text": token_string(*parts),
        },
    )


def build_actions() -> list[dict[str, Any]]:
    ask_id = stable_uuid("ask-reminder")
    delivery_id = stable_uuid("delivery-id")
    token_id = stable_uuid("github-token")
    github_url_id = stable_uuid("github-url")
    issue_body_id = stable_uuid("issue-body")
    issue_title_id = stable_uuid("issue-title")
    issue_response_id = stable_uuid("issue-response")
    issue_number_id = stable_uuid("issue-number")
    cockpit_url_id = stable_uuid("cockpit-url")
    cockpit_response_id = stable_uuid("cockpit-response")
    receipt_id = stable_uuid("cockpit-receipt-id")
    receipt_text_id = stable_uuid("cockpit-receipt-text")
    issue_if_group = stable_uuid("issue-confirmed-if")
    receipt_if_group = stable_uuid("receipt-matches-if")

    actions = [
        comment(
            "Samantha – důležité připomenutí.\n\n"
            "Nejprve uloží text do soukromého GitHub Issues inboxu. Potom zkusí přímé "
            "doručení do Cockpitu přes Tailscale. Mac uzavře GitHub Issue až po lokálním "
            "převzetí stejného delivery_id."
        ),
        comment(
            "Shortcuts generated by Shortcuts Playground. May contain mistakes. Always check "
            "the shortcut's actions first.\n\n"
            "This shortcut was created via the following user prompt:\n\n"
            "> Vytvoř iPhone zkratku pro důležité připomenutí: nejprve bezpečně založ "
            "Issue v soukromém GitHub fallback inboxu, potom zkus přímé doručení do "
            "Cockpitu přes Tailscale a považuj doručení za jisté jen při přesné shodě delivery_id."
        ),
        comment("1. Zeptej se na text a vytvoř jedinečné delivery_id."),
        action(
            "is.workflow.actions.ask",
            {
                "CustomOutputName": "Připomenutí",
                "UUID": ask_id,
                "WFAskActionPrompt": "Co je důležité připomenout?",
                "WFInputType": "Text",
            },
        ),
        action(
            "is.workflow.actions.gettext",
            {
                "CustomOutputName": "Delivery ID",
                "UUID": delivery_id,
                "WFTextActionText": current_date_token_string(
                    "samantha-", date_format="yyyyMMddHHmmssSSS"
                ),
            },
        ),
        comment(
            "2. GitHub token musí být fine-grained a omezený jen na tento soukromý repozitář "
            "s oprávněním Issues: Read and write. Vytvoření tokenu: "
            "https://github.com/settings/personal-access-tokens/new"
        ),
        action(
            "is.workflow.actions.gettext",
            {
                "CustomOutputName": "GitHub token",
                "UUID": token_id,
                "WFTextActionText": "github_pat_REPLACE_ME",
            },
        ),
        action(
            "is.workflow.actions.url",
            {
                "CustomOutputName": "GitHub Issues URL",
                "UUID": github_url_id,
                "WFURLActionURL": "https://api.github.com/repos/OWNER/REPOSITORY/issues",
            },
        ),
        action(
            "is.workflow.actions.gettext",
            {
                "CustomOutputName": "GitHub Issue body",
                "UUID": issue_body_id,
                "WFTextActionText": token_string(
                    "Samantha urgent reminder v1\ndelivery_id: ",
                    (delivery_id, "Delivery ID"),
                    "\ncreated_at:\npriority: urgent\n\n",
                    (ask_id, "Připomenutí"),
                ),
            },
        ),
        action(
            "is.workflow.actions.gettext",
            {
                "CustomOutputName": "GitHub Issue title",
                "UUID": issue_title_id,
                "WFTextActionText": token_string(
                    "[Samantha Inbox] ",
                    (delivery_id, "Delivery ID"),
                ),
            },
        ),
        action(
            "is.workflow.actions.downloadurl",
            {
                "CustomOutputName": "GitHub Issue response",
                "UUID": issue_response_id,
                "WFHTTPBodyType": "JSON",
                "WFHTTPHeaders": dictionary_items(
                    [
                        ("Accept", token_string("application/vnd.github+json")),
                        (
                            "Authorization",
                            token_string("Bearer ", (token_id, "GitHub token")),
                        ),
                        ("X-GitHub-Api-Version", token_string("2026-03-10")),
                    ]
                ),
                "WFHTTPMethod": "POST",
                "WFJSONValues": dictionary_items(
                    [
                        ("title", token_string((issue_title_id, "GitHub Issue title"))),
                        ("body", token_string((issue_body_id, "GitHub Issue body"))),
                    ]
                ),
                # iOS renders the URL field only when a magic variable is
                # serialized as a token string, even when it is the sole value.
                "WFURL": token_string((github_url_id, "GitHub Issues URL")),
            },
        ),
        action(
            "is.workflow.actions.getvalueforkey",
            {
                "CustomOutputName": "GitHub Issue number",
                "UUID": issue_number_id,
                "WFDictionaryKey": "number",
                "WFGetDictionaryValueType": "Value",
                "WFInput": token_attachment(issue_response_id, "GitHub Issue response"),
            },
        ),
        comment(
            "3. Pokračuj k přímému doručení jen tehdy, když GitHub vrátil číslo vytvořené Issue.\n"
            "• Když Mac spí, síťová akce Cockpitu skončí chybou a Issue zůstane otevřená.\n"
            "• Nic se automaticky neposílá třetí cestou."
        ),
        action(
            "is.workflow.actions.conditional",
            {
                "GroupingIdentifier": issue_if_group,
                "WFCondition": 100,
                "WFControlFlowMode": 0,
                "WFInput": condition_input(issue_number_id, "GitHub Issue number"),
            },
        ),
        comment("4. Zkus přímé doručení stejného textu a stejného delivery_id přes Tailscale."),
        action(
            "is.workflow.actions.url",
            {
                "CustomOutputName": "Cockpit delivery URL",
                "UUID": cockpit_url_id,
                "WFURLActionURL": (
                    "https://cockpit-host.tailnet-name.ts.net/api/urgent-reminders/deliver"
                ),
            },
        ),
        action(
            "is.workflow.actions.downloadurl",
            {
                "CustomOutputName": "Odpověď Cockpitu",
                "UUID": cockpit_response_id,
                "WFHTTPBodyType": "JSON",
                "WFHTTPMethod": "POST",
                "WFJSONValues": dictionary_items(
                    [
                        ("text", token_string((ask_id, "Připomenutí"))),
                        ("priority", token_string("urgent")),
                        ("delivery_id", token_string((delivery_id, "Delivery ID"))),
                    ]
                ),
                "WFURL": token_string((cockpit_url_id, "Cockpit delivery URL")),
            },
        ),
        action(
            "is.workflow.actions.getvalueforkey",
            {
                "CustomOutputName": "Potvrzené delivery_id",
                "UUID": receipt_id,
                "WFDictionaryKey": "delivery_id",
                "WFGetDictionaryValueType": "Value",
                "WFInput": token_attachment(cockpit_response_id, "Odpověď Cockpitu"),
            },
        ),
        action(
            "is.workflow.actions.gettext",
            {
                "CustomOutputName": "Potvrzené delivery_id jako text",
                "UUID": receipt_text_id,
                "WFTextActionText": token_string((receipt_id, "Potvrzené delivery_id")),
            },
        ),
        comment(
            "5. Přímé doručení potvrď jen při přesné shodě delivery_id.\n"
            "• Shoda: Cockpit připomenutí převzal.\n"
            "• Neshoda: stav je nejistý a GitHub Issue zůstává bezpečně otevřená."
        ),
        action(
            "is.workflow.actions.conditional",
            {
                "GroupingIdentifier": receipt_if_group,
                "WFCondition": 4,
                "WFConditionalActionString": token_string((delivery_id, "Delivery ID")),
                "WFControlFlowMode": 0,
                "WFInput": condition_input(
                    receipt_text_id,
                    "Potvrzené delivery_id jako text",
                ),
            },
        ),
        show_result(
            "direct-success",
            "Doručeno přímo do Cockpitu. GitHub záloha #",
            (issue_number_id, "GitHub Issue number"),
            " se po převzetí na Macu automaticky uzavře.",
        ),
        action(
            "is.workflow.actions.conditional",
            {"GroupingIdentifier": receipt_if_group, "WFControlFlowMode": 1},
        ),
        show_result(
            "delivery-unknown",
            "Doručení je nejisté. GitHub záloha #",
            (issue_number_id, "GitHub Issue number"),
            " zůstává otevřená.",
        ),
        action(
            "is.workflow.actions.conditional",
            {"GroupingIdentifier": receipt_if_group, "WFControlFlowMode": 2},
        ),
        action(
            "is.workflow.actions.conditional",
            {"GroupingIdentifier": issue_if_group, "WFControlFlowMode": 1},
        ),
        show_result(
            "github-unknown",
            "GitHub nepotvrdil vytvoření zálohy. Připomenutí neposílám dál; spusť zkratku znovu.",
        ),
        action(
            "is.workflow.actions.conditional",
            {"GroupingIdentifier": issue_if_group, "WFControlFlowMode": 2},
        ),
    ]
    return actions


def build_workflow() -> dict[str, Any]:
    actions = build_actions()
    return {
        "WFWorkflowActions": actions,
        "WFWorkflowClientVersion": "2700.0.4",
        "WFWorkflowHasOutputFallback": False,
        "WFWorkflowIcon": {
            "WFWorkflowIconGlyphNumber": 61486,
            "WFWorkflowIconStartColor": 431817727,
        },
        "WFWorkflowImportQuestions": [
            {
                "ActionIndex": 6,
                "Category": "Parameter",
                "DefaultValue": "github_pat_REPLACE_ME",
                "ParameterKey": "WFTextActionText",
                "Text": (
                    "Vlož fine-grained GitHub token omezený jen na soukromý inbox "
                    "s oprávněním Issues: Read and write"
                ),
            },
            {
                "ActionIndex": 7,
                "Category": "Parameter",
                "DefaultValue": "https://api.github.com/repos/OWNER/REPOSITORY/issues",
                "ParameterKey": "WFURLActionURL",
                "Text": "Vlož GitHub API URL soukromého inboxu zakončenou /issues",
            },
            {
                "ActionIndex": 15,
                "Category": "Parameter",
                "DefaultValue": (
                    "https://cockpit-host.tailnet-name.ts.net/api/urgent-reminders/deliver"
                ),
                "ParameterKey": "WFURLActionURL",
                "Text": (
                    "Vlož celou Tailscale HTTPS adresu Cockpitu zakončenou "
                    "/api/urgent-reminders/deliver"
                ),
            },
        ],
        "WFWorkflowInputContentItemClasses": [],
        "WFWorkflowMinimumClientVersion": 900,
        "WFWorkflowMinimumClientVersionString": "900",
        "WFWorkflowName": WORKFLOW_NAME,
        "WFWorkflowOutputContentItemClasses": [],
        "WFWorkflowTypes": [],
    }


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("wb") as handle:
        plistlib.dump(build_workflow(), handle, fmt=plistlib.FMT_XML, sort_keys=False)
    print(OUTPUT_PATH)


if __name__ == "__main__":
    main()
