window.FOREST_SCHOOL_AUDIO_MANIFEST = {
  "dialogue": {
    "cs": {
      "ui::Chceš pokračovat další lekcí? Stiskňi ano. Pokud chceš opakovat, stiskňi ne.": "audio/czech/forest_school_lesson_choice_cz.mp3",
      "ui::Je to správně? Pokud ano, klikňi na jes. Pokud ne, klikňi na nou.": "audio/czech/forest_school_help_cz.mp3",
      "ui::Nejprve si ukážeme slovíčka z této lekce. Poslechněte si anglické slovíčko a opakujte si výslovnost.": "audio/czech/forest_school_lesson_preview_cz.mp3",
      "word-apple::jablko": "audio/czech/forest_school_word_apple_cz.mp3",
      "word-bag::batoh": "audio/czech/forest_school_word_bag_cz.mp3",
      "word-ball::míč": "audio/czech/forest_school_word_ball_cz.mp3",
      "word-banana::banán": "audio/czech/forest_school_word_banana_cz.mp3",
      "word-bed::postel": "audio/czech/forest_school_word_bed_cz.mp3",
      "word-bike::kolo": "audio/czech/forest_school_word_bike_cz.mp3",
      "word-block::kostka": "audio/czech/forest_school_word_block_cz.mp3",
      "word-boat::loď": "audio/czech/forest_school_word_boat_cz.mp3",
      "word-book::kniha": "audio/czech/forest_school_word_book_cz.mp3",
      "word-boots::holinky": "audio/czech/forest_school_word_boots_cz.mp3",
      "word-box::krabice": "audio/czech/forest_school_word_box_cz.mp3",
      "word-bread::chleba": "audio/czech/forest_school_word_bread_cz.mp3",
      "word-bus::autobus": "audio/czech/forest_school_word_bus_cz.mp3",
      "word-cake::dort": "audio/czech/forest_school_word_cake_cz.mp3",
      "word-cap::čepice": "audio/czech/forest_school_word_hat_cz.mp3",
      "word-car::auto": "audio/czech/forest_school_word_car_cz.mp3",
      "word-carrot::mrkev": "scene02_sunnys_lost_nuts/audio/czech/scene02_vocab_carrot_cz.mp3",
      "word-chair::židle": "audio/czech/forest_school_word_chair_cz.mp3",
      "word-cloud::mrak": "audio/czech/forest_school_word_cloud_cz.mp3",
      "word-cookie::sušenka": "audio/czech/forest_school_word_cookie_cz.mp3",
      "word-corn::kukuřice": "audio/czech/forest_school_word_corn_cz.mp3",
      "word-cup::hrnek": "audio/czech/forest_school_word_cup_cz.mp3",
      "word-doll::panenka": "audio/czech/forest_school_word_doll_cz.mp3",
      "word-door::dveře": "scene03_journey_to_the_lake/audio/czech/scene03_ui_door_cz.mp3",
      "word-flower::kytka": "audio/czech/forest_school_word_flower_cz.mp3",
      "word-fork::vidlička": "audio/czech/forest_school_word_fork_cz.mp3",
      "word-grape::hroznové víno": "audio/czech/forest_school_word_grape_cz.mp3",
      "word-hat::čepice": "audio/czech/forest_school_word_hat_cz.mp3",
      "word-house::dům": "audio/czech/forest_school_word_house_cz.mp3",
      "word-key::klíč": "audio/czech/forest_school_word_key_cz.mp3",
      "word-kite::drak": "audio/czech/forest_school_word_kite_cz.mp3",
      "word-lamp::lampa": "audio/czech/forest_school_word_lamp_cz.mp3",
      "word-leaf::list": "audio/czech/forest_school_word_leaf_cz.mp3",
      "word-map::mapa": "scene02_sunnys_lost_nuts/audio/czech/scene02_vocab_map_cz.mp3",
      "word-milk::mléko": "audio/czech/forest_school_word_milk_cz.mp3",
      "word-moon::měsíc": "audio/czech/forest_school_word_moon_cz.mp3",
      "word-orange::pomeranč": "audio/czech/forest_school_word_orange_cz.mp3",
      "word-pants::kalhoty": "audio/czech/forest_school_word_pants_cz.mp3",
      "word-pea::hrášek": "audio/czech/forest_school_word_pea_cz.mp3",
      "word-pencil::tužka": "audio/czech/forest_school_word_pencil_cz.mp3",
      "word-pillow::polštář": "audio/czech/forest_school_word_pillow_cz.mp3",
      "word-plane::letadlo": "audio/czech/forest_school_word_plane_cz.mp3",
      "word-plate::talíř": "audio/czech/forest_school_word_plate_cz.mp3",
      "word-robot::robot": "audio/czech/forest_school_word_robot_cz.mp3",
      "word-rocket::raketa": "audio/czech/forest_school_word_rocket_cz.mp3",
      "word-shoe::bota": "audio/czech/forest_school_word_shoe_cz.mp3",
      "word-soap::mýdlo": "audio/czech/forest_school_word_soap_cz.mp3",
      "word-sock::ponožka": "audio/czech/forest_school_word_sock_cz.mp3",
      "word-spoon::lžička": "audio/czech/forest_school_word_spoon_cz.mp3",
      "word-star::hvězda": "audio/czech/forest_school_word_star_cz.mp3",
      "word-stick::klacek": "audio/czech/forest_school_word_stick_cz.mp3",
      "word-stone::kámen": "audio/czech/forest_school_word_stone_cz.mp3",
      "word-sun::slunce": "audio/czech/forest_school_word_sun_cz.mp3",
      "word-table::stůl": "audio/czech/forest_school_word_table_cz.mp3",
      "word-toy::hračka": "audio/czech/forest_school_word_toy_cz.mp3",
      "word-train::vlak": "audio/czech/forest_school_word_train_cz.mp3",
      "word-tree::strom": "audio/czech/forest_school_word_tree_cz.mp3",
      "word-truck::náklaďák": "audio/czech/forest_school_word_truck_cz.mp3",
      "word-water::voda": "scene03_journey_to_the_lake/audio/czech/scene03_ui_water_cz.mp3",
      "word-window::okno": "audio/czech/forest_school_word_window_cz.mp3"
    },
    "en": {
      "answer::no": "audio/english/forest_school_answer_no_en.mp3",
      "answer::yes": "audio/english/forest_school_answer_yes_en.mp3",
      "benji::No, it isn't.": "audio/english/forest_school_benji_no_it_isnt.mp3",
      "bunny::Yes, it is.": "audio/english/forest_school_bunny_yes_it_is.mp3",
      "owl::Excellent.": "audio/english/forest_school_excellent_en.mp3",
      "owl::Great job. Forest school is finished.": "audio/english/forest_school_finished_en.mp3",
      "owl::Is this a apple?": "audio/english/forest_school_question_apple_en.mp3",
      "owl::Is this a bag?": "audio/english/forest_school_question_bag_en.mp3",
      "owl::Is this a ball?": "audio/english/forest_school_question_ball_en.mp3",
      "owl::Is this a banana?": "audio/english/forest_school_question_banana_en.mp3",
      "owl::Is this a bed?": "audio/english/forest_school_question_bed_en.mp3",
      "owl::Is this a bike?": "audio/english/forest_school_question_bike_en.mp3",
      "owl::Is this a block?": "audio/english/forest_school_question_block_en.mp3",
      "owl::Is this a boat?": "audio/english/forest_school_question_boat_en.mp3",
      "owl::Is this a book?": "audio/english/forest_school_question_book_en.mp3",
      "owl::Is this a boots?": "audio/english/forest_school_question_boots_en.mp3",
      "owl::Is this a box?": "audio/english/forest_school_question_box_en.mp3",
      "owl::Is this a bread?": "audio/english/forest_school_question_bread_en.mp3",
      "owl::Is this a bus?": "audio/english/forest_school_question_bus_en.mp3",
      "owl::Is this a cake?": "audio/english/forest_school_question_cake_en.mp3",
      "owl::Is this a cap?": "audio/english/forest_school_question_cap_en.mp3",
      "owl::Is this a car?": "audio/english/forest_school_question_car_en.mp3",
      "owl::Is this a carrot?": "audio/english/forest_school_question_carrot_en.mp3",
      "owl::Is this a chair?": "audio/english/forest_school_question_chair_en.mp3",
      "owl::Is this a cloud?": "audio/english/forest_school_question_cloud_en.mp3",
      "owl::Is this a cookie?": "audio/english/forest_school_question_cookie_en.mp3",
      "owl::Is this a corn?": "audio/english/forest_school_question_corn_en.mp3",
      "owl::Is this a cup?": "audio/english/forest_school_question_cup_en.mp3",
      "owl::Is this a doll?": "audio/english/forest_school_question_doll_en.mp3",
      "owl::Is this a door?": "audio/english/forest_school_question_door_en.mp3",
      "owl::Is this a flower?": "audio/english/forest_school_question_flower_en.mp3",
      "owl::Is this a fork?": "audio/english/forest_school_question_fork_en.mp3",
      "owl::Is this a grape?": "audio/english/forest_school_question_grape_en.mp3",
      "owl::Is this a hat?": "audio/english/forest_school_question_hat_en.mp3",
      "owl::Is this a house?": "audio/english/forest_school_question_house_en.mp3",
      "owl::Is this a key?": "audio/english/forest_school_question_key_en.mp3",
      "owl::Is this a kite?": "audio/english/forest_school_question_kite_en.mp3",
      "owl::Is this a lamp?": "audio/english/forest_school_question_lamp_en.mp3",
      "owl::Is this a leaf?": "audio/english/forest_school_question_leaf_en.mp3",
      "owl::Is this a map?": "audio/english/forest_school_question_map_en.mp3",
      "owl::Is this a milk?": "audio/english/forest_school_question_milk_en.mp3",
      "owl::Is this a moon?": "audio/english/forest_school_question_moon_en.mp3",
      "owl::Is this a orange?": "audio/english/forest_school_question_orange_en.mp3",
      "owl::Is this a pants?": "audio/english/forest_school_question_pants_en.mp3",
      "owl::Is this a pea?": "audio/english/forest_school_question_pea_en.mp3",
      "owl::Is this a pencil?": "audio/english/forest_school_question_pencil_en.mp3",
      "owl::Is this a pillow?": "audio/english/forest_school_question_pillow_en.mp3",
      "owl::Is this a plane?": "audio/english/forest_school_question_plane_en.mp3",
      "owl::Is this a plate?": "audio/english/forest_school_question_plate_en.mp3",
      "owl::Is this a robot?": "audio/english/forest_school_question_robot_en.mp3",
      "owl::Is this a rocket?": "audio/english/forest_school_question_rocket_en.mp3",
      "owl::Is this a shoe?": "audio/english/forest_school_question_shoe_en.mp3",
      "owl::Is this a soap?": "audio/english/forest_school_question_soap_en.mp3",
      "owl::Is this a sock?": "audio/english/forest_school_question_sock_en.mp3",
      "owl::Is this a spoon?": "audio/english/forest_school_question_spoon_en.mp3",
      "owl::Is this a star?": "audio/english/forest_school_question_star_en.mp3",
      "owl::Is this a stick?": "audio/english/forest_school_question_stick_en.mp3",
      "owl::Is this a stone?": "audio/english/forest_school_question_stone_en.mp3",
      "owl::Is this a sun?": "audio/english/forest_school_question_sun_en.mp3",
      "owl::Is this a table?": "audio/english/forest_school_question_table_en.mp3",
      "owl::Is this a toy?": "audio/english/forest_school_question_toy_en.mp3",
      "owl::Is this a train?": "audio/english/forest_school_question_train_en.mp3",
      "owl::Is this a tree?": "audio/english/forest_school_question_tree_en.mp3",
      "owl::Is this a truck?": "audio/english/forest_school_question_truck_en.mp3",
      "owl::Is this a water?": "audio/english/forest_school_question_water_en.mp3",
      "owl::Is this a window?": "audio/english/forest_school_question_window_en.mp3",
      "owl::Lesson eight": "audio/english/forest_school_lesson_08_title_en.mp3",
      "owl::Lesson eleven": "audio/english/forest_school_lesson_11_title_en.mp3",
      "owl::Lesson five": "audio/english/forest_school_lesson_05_title_en.mp3",
      "owl::Lesson four": "audio/english/forest_school_lesson_04_title_en.mp3",
      "owl::Lesson nine": "audio/english/forest_school_lesson_09_title_en.mp3",
      "owl::Lesson one": "audio/english/forest_school_lesson_01_title_en.mp3",
      "owl::Lesson seven": "audio/english/forest_school_lesson_07_title_en.mp3",
      "owl::Lesson six": "audio/english/forest_school_lesson_06_title_en.mp3",
      "owl::Lesson ten": "audio/english/forest_school_lesson_10_title_en.mp3",
      "owl::Lesson three": "audio/english/forest_school_lesson_03_title_en.mp3",
      "owl::Lesson twelve": "audio/english/forest_school_lesson_12_title_en.mp3",
      "owl::Lesson two": "audio/english/forest_school_lesson_02_title_en.mp3",
      "owl::Try again.": "scene02_sunnys_lost_nuts/audio/english/scene02_try_again_en.mp3",
      "owl::Welcome to forest school.": "audio/english/forest_school_welcome_en.mp3",
      "owl::Will you try?": "audio/english/forest_school_will_you_try_en.mp3",
      "word-apple::apple": "audio/english/forest_school_word_apple_en.mp3",
      "word-bag::bag": "scene02_sunnys_lost_nuts/audio/english/scene02_vocab_bag_en.mp3",
      "word-ball::ball": "audio/english/forest_school_word_ball_en.mp3",
      "word-banana::banana": "audio/english/forest_school_word_banana_en.mp3",
      "word-bed::bed": "audio/english/forest_school_word_bed_en.mp3",
      "word-bike::bike": "audio/english/forest_school_word_bike_en.mp3",
      "word-block::block": "audio/english/forest_school_word_block_en.mp3",
      "word-boat::boat": "audio/english/forest_school_word_boat_en.mp3",
      "word-book::book": "audio/english/forest_school_word_book_en.mp3",
      "word-boots::boots": "audio/english/forest_school_word_boots_en.mp3",
      "word-box::box": "audio/english/forest_school_word_box_en.mp3",
      "word-bread::bread": "audio/english/forest_school_word_bread_en.mp3",
      "word-bus::bus": "audio/english/forest_school_word_bus_en.mp3",
      "word-cake::cake": "audio/english/forest_school_word_cake_en.mp3",
      "word-cap::cap": "audio/english/forest_school_word_cap_en.mp3",
      "word-car::car": "audio/english/forest_school_word_car_en.mp3",
      "word-carrot::carrot": "scene02_sunnys_lost_nuts/audio/english/scene02_vocab_carrot_en.mp3",
      "word-chair::chair": "audio/english/forest_school_word_chair_en.mp3",
      "word-cloud::cloud": "audio/english/forest_school_word_cloud_en.mp3",
      "word-cookie::cookie": "audio/english/forest_school_word_cookie_en.mp3",
      "word-corn::corn": "audio/english/forest_school_word_corn_en.mp3",
      "word-cup::cup": "audio/english/forest_school_word_cup_en.mp3",
      "word-doll::doll": "audio/english/forest_school_word_doll_en.mp3",
      "word-door::door": "scene03_journey_to_the_lake/audio/english/scene03_ui_door_en.mp3",
      "word-flower::flower": "audio/english/forest_school_word_flower_en.mp3",
      "word-fork::fork": "audio/english/forest_school_word_fork_en.mp3",
      "word-grape::grape": "audio/english/forest_school_word_grape_en.mp3",
      "word-hat::hat": "audio/english/forest_school_word_hat_en.mp3",
      "word-house::house": "audio/english/forest_school_word_house_en.mp3",
      "word-key::key": "audio/english/forest_school_word_key_en.mp3",
      "word-kite::kite": "audio/english/forest_school_word_kite_en.mp3",
      "word-lamp::lamp": "audio/english/forest_school_word_lamp_en.mp3",
      "word-leaf::leaf": "audio/english/forest_school_word_leaf_en.mp3",
      "word-map::map": "scene02_sunnys_lost_nuts/audio/english/scene02_vocab_map_en.mp3",
      "word-milk::milk": "audio/english/forest_school_word_milk_en.mp3",
      "word-moon::moon": "audio/english/forest_school_word_moon_en.mp3",
      "word-orange::orange": "audio/english/forest_school_word_orange_en.mp3",
      "word-pants::pants": "audio/english/forest_school_word_pants_en.mp3",
      "word-pea::pea": "audio/english/forest_school_word_pea_en.mp3",
      "word-pencil::pencil": "audio/english/forest_school_word_pencil_en.mp3",
      "word-pillow::pillow": "audio/english/forest_school_word_pillow_en.mp3",
      "word-plane::plane": "audio/english/forest_school_word_plane_en.mp3",
      "word-plate::plate": "audio/english/forest_school_word_plate_en.mp3",
      "word-robot::robot": "audio/english/forest_school_word_robot_en.mp3",
      "word-rocket::rocket": "audio/english/forest_school_word_rocket_en.mp3",
      "word-shoe::shoe": "audio/english/forest_school_word_shoe_en.mp3",
      "word-soap::soap": "audio/english/forest_school_word_soap_en.mp3",
      "word-sock::sock": "audio/english/forest_school_word_sock_en.mp3",
      "word-spoon::spoon": "audio/english/forest_school_word_spoon_en.mp3",
      "word-star::star": "audio/english/forest_school_word_star_en.mp3",
      "word-stick::stick": "audio/english/forest_school_word_stick_en.mp3",
      "word-stone::stone": "audio/english/forest_school_word_stone_en.mp3",
      "word-sun::sun": "audio/english/forest_school_word_sun_en.mp3",
      "word-table::table": "audio/english/forest_school_word_table_en.mp3",
      "word-toy::toy": "audio/english/forest_school_word_toy_en.mp3",
      "word-train::train": "audio/english/forest_school_word_train_en.mp3",
      "word-tree::tree": "audio/english/forest_school_word_tree_en.mp3",
      "word-truck::truck": "audio/english/forest_school_word_truck_en.mp3",
      "word-water::water": "scene03_journey_to_the_lake/audio/english/scene03_ui_water_en.mp3",
      "word-window::window": "audio/english/forest_school_word_window_en.mp3"
    }
  },
  "rate": "-10%",
  "schemaVersion": 1,
  "stats": {
    "audioFiles": 203,
    "audioReferences": 204,
    "czechFiles": 62,
    "englishFiles": 141,
    "lessons": 12,
    "objects": 60,
    "preservedExistingFiles": 13
  },
  "version": "20260830fixed1",
  "voices": {
    "cs-CZ-VlastaNeural": {
      "id": "cs-CZ-VlastaNeural",
      "label": "Vlasta"
    },
    "en-US-JennyNeural": {
      "id": "en-US-JennyNeural",
      "label": "Jenny"
    },
    "preserved-existing-Czech": {
      "id": "preserved-existing-Czech",
      "label": "Existing approved Czech"
    },
    "preserved-existing-English": {
      "id": "preserved-existing-English",
      "label": "Existing approved English"
    }
  }
};
