from __future__ import annotations

from app.capabilities.models import (
    AuditPolicy,
    CapabilityRecord,
    ConfirmationPolicy,
    MobilePolicy,
    RiskLevel,
    VoicePolicy,
)


CAPABILITIES: tuple[CapabilityRecord, ...] = (
    CapabilityRecord(
        capability_id="git_safety_check",
        label="Git staged safety check",
        risk=RiskLevel.READ_ONLY,
        reads=(
            "git staged file list",
            "branch guard state",
            "memory/infrastructure/git_branch_archive.md",
        ),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="scripts/git_safety_check.py",
        notes="Checks staged content and branch risk before commit.",
    ),
    CapabilityRecord(
        capability_id="work_context_guard",
        label="Work context guard",
        risk=RiskLevel.READ_ONLY,
        reads=(
            "git status",
            "branch guard state",
            "merge/rebase/cherry-pick/revert markers",
        ),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="scripts/work_context_guard.py",
        notes="Read-only guard before switching topics or starting a new session.",
    ),
    CapabilityRecord(
        capability_id="search_memory",
        label="Search Samantha markdown memory",
        risk=RiskLevel.READ_ONLY,
        reads=("memory markdown snippets", "memory source-type index"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="search_memory",
        notes="Returns relevant excerpts from git-safe memory files; private vault and full emails are outside scope.",
    ),
    CapabilityRecord(
        capability_id="memory_status",
        label="Show Samantha memory status",
        risk=RiskLevel.READ_ONLY,
        reads=("memory index metadata", "startup context size", "active reminders/activity summaries"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="memory_status",
        notes="Safe diagnostics only; does not read private vault documents or email bodies.",
    ),
    CapabilityRecord(
        capability_id="samantha_health_check",
        label="Run Samantha health check",
        risk=RiskLevel.READ_ONLY,
        reads=("git status", "memory project registry", "memory index reminder markers"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="samantha_health_check",
        notes="Read-only operational status for repo cleanliness, pending work and reminder pressure.",
    ),
    CapabilityRecord(
        capability_id="samantha_quantitative_status",
        label="Show Samantha quantitative status",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("git tracked file list", "non-private project file sizes and line counts"),
        writes=("optional data/metrics aggregate JSONL row when save=True",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="samantha_quantitative_status",
        notes="Default is read-only; save=True appends aggregate metrics without filenames or private content.",
    ),
    CapabilityRecord(
        capability_id="samantha_system_reports",
        label="List Samantha system reports",
        risk=RiskLevel.READ_ONLY,
        reads=("static system report registry",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="samantha_system_reports",
        notes="Read-only catalogue of report commands and Samantha tools.",
    ),
    CapabilityRecord(
        capability_id="family_calendar_delivery_readiness",
        label="Inspect family-calendar delivery readiness",
        risk=RiskLevel.READ_ONLY,
        reads=(
            "private family-calendar delivery configuration validation",
            "private delivery state aggregates",
            "dedicated local planner metadata",
            "Keychain credential item existence without secret value",
        ),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="family_calendar_delivery_readiness",
        notes="Returns only aggregate blockers; never reads the credential value, mutates recovery state, or calls SMTP.",
    ),
    CapabilityRecord(
        capability_id="samantha_capability_audit",
        label="Run Samantha capability audit",
        risk=RiskLevel.READ_ONLY,
        reads=("agent tool list", "capability registry", "workflow command registry"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="samantha_capability_audit",
        notes="Read-only coverage and gap report for tools, workflows and capability records.",
    ),
    CapabilityRecord(
        capability_id="samantha_project_audit",
        label="Run Samantha project/layer audit",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("ACTIVE_PROJECTS.md", "MEMORY_INDEX.md", "health check", "capability audit", "aggregate quantitative status"),
        writes=("optional memory/reports git-safe audit text when save=True",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="samantha_project_audit",
        notes="Default is read-only; save=True writes only a git-safe report without private vault or full email content.",
    ),
    CapabilityRecord(
        capability_id="git_push_main_after_guard",
        label="Routine push to origin main after green guard",
        risk=RiskLevel.GIT_PUBLISH,
        reads=(
            "git branch and upstream state",
            "git working tree state",
            "last commit file list",
        ),
        writes=("git push origin main",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="scripts/git_push_guard.py + git push origin main",
        notes="Allowed without another question only after git_push_guard.py reports routine push allowed.",
        metadata={"requires_green_guard": "true", "allowed_remote": "origin", "allowed_branch": "main"},
    ),
    CapabilityRecord(
        capability_id="copy_downloads_files_to_knowledge_inbox",
        label="Copy selected Downloads files to private knowledge inbox",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("selected top-level Downloads files metadata and bytes",),
        writes=("data/private/knowledge_inbox/incoming copied files",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="copy_downloads_files_to_knowledge_inbox",
        notes="Copies only explicitly selected relative files from Downloads; does not read content for summarization.",
    ),
    CapabilityRecord(
        capability_id="samantha_knowledge_inbox_inventory",
        label="Show private knowledge inbox inventory",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("data/private/knowledge_inbox file metadata",),
        writes=("data/private/knowledge_inbox folder structure when missing",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="samantha_knowledge_inbox_inventory",
        notes="Lists private inbox metadata only; wrapper may create missing ignored inbox folders.",
    ),
    CapabilityRecord(
        capability_id="samantha_downloads_inventory",
        label="Show Downloads inventory for knowledge inbox",
        risk=RiskLevel.READ_ONLY,
        reads=("top-level Downloads file metadata",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="samantha_downloads_inventory",
        notes="Lists names, suffixes, sizes and modified times only; does not read file contents.",
    ),
    CapabilityRecord(
        capability_id="iphone_shortcuts_playground_status",
        label="Show iPhone Shortcuts Playground status",
        risk=RiskLevel.READ_ONLY,
        reads=("local CLI availability", "Shortcuts Playground plugin paths", "private request folder existence"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="iphone_shortcuts_playground_status",
        notes="Read-only readiness check; shortcut request drafting remains a separate confirmed capability.",
    ),
    CapabilityRecord(
        capability_id="prepare_iphone_shortcut",
        label="Prepare private iPhone Shortcut request draft",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("shortcut name, purpose and details from current request",),
        writes=("data/private/iphone_shortcuts/requests markdown draft",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="prepare_iphone_shortcut",
        notes="Without confirmation returns only a preview prompt; confirmed path writes a private request draft, not a shortcut file.",
    ),
    CapabilityRecord(
        capability_id="quick_notes_action_status",
        label="Quick Notes action inbox",
        risk=RiskLevel.LOCAL_WRITE,
        reads=(
            "data/private/quick_notes metadata",
            "selected quick note text summaries",
        ),
        writes=("data/private/quick_notes/index.json synced metadata",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="quick_notes_action_status",
        notes="Syncs the private quick-notes index, then shows an overview for choosing later confirmed actions.",
    ),
    CapabilityRecord(
        capability_id="list_quick_notes",
        label="List Quick Notes inbox",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iCloud Shortcuts quick note text snippets", "data/private/quick_notes metadata"),
        writes=("data/private/quick_notes/index.json synced metadata",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="list_quick_notes",
        notes="Syncs the private quick-notes index, then lists active note snippets and detail commands.",
    ),
    CapabilityRecord(
        capability_id="show_quick_note_detail",
        label="Show Quick Note detail",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("selected iCloud Shortcuts quick note text", "data/private/quick_notes metadata"),
        writes=("data/private/quick_notes/index.json synced metadata",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="show_quick_note_detail",
        notes="Syncs the private quick-notes index and reads one selected inbox note; performs no external action.",
    ),
    CapabilityRecord(
        capability_id="restore_path_from_backup",
        label="Restore one PythonMF path from backup",
        risk=RiskLevel.DESTRUCTIVE,
        reads=("selected Samantha backup snapshot", "target path metadata"),
        writes=("restored PythonMF file or folder", ".before_restore copy of previous target"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="restore_path_from_backup",
        notes="Restores only a safe relative path after preview; sensitive paths require extra recovery wording.",
    ),
    CapabilityRecord(
        capability_id="list_backup_snapshots",
        label="List backup snapshots",
        risk=RiskLevel.READ_ONLY,
        reads=("Samantha backup snapshot directories", "backup manifest metadata"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="list_backup_snapshots",
        notes="Lists available backup snapshots and manifest metadata; does not restore or modify files.",
    ),
    CapabilityRecord(
        capability_id="preview_backup_restore",
        label="Preview restore from backup",
        risk=RiskLevel.READ_ONLY,
        reads=("selected backup snapshot path metadata", "target PythonMF path metadata"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="preview_backup_restore",
        notes="Preview only; restore remains a separate destructive capability with explicit confirmation.",
    ),
    CapabilityRecord(
        capability_id="list_workflow_commands",
        label="List registered workflow commands",
        risk=RiskLevel.READ_ONLY,
        reads=("workflow command registry",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="list_workflow_commands",
        notes="Lists exact registered commands and their risk metadata; does not execute anything.",
    ),
    CapabilityRecord(
        capability_id="preview_workflow_command",
        label="Preview registered workflow command",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("workflow command registry", "workflow preflight state"),
        writes=("data/workflows/pending_command.json for confirmation-gated commands",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="preview_workflow_command",
        notes="Preview only; may save the exact pending command so a later confirmation cannot drift.",
    ),
    CapabilityRecord(
        capability_id="run_workflow_command",
        label="Run registered local workflow command",
        risk=RiskLevel.SYSTEM_CHANGE,
        reads=("workflow command registry", "pending workflow confirmation card"),
        writes=("registered command side effects", "workflow pending-command state"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="run_workflow_command",
        notes="Runs only registered argv commands; commands marked as requiring confirmation need a current-message confirmation.",
    ),
    CapabilityRecord(
        capability_id="send_prepared_email_draft",
        label="Send prepared email draft",
        risk=RiskLevel.EXTERNAL_SEND,
        reads=("local outbox draft",),
        writes=("SMTP send", "best-effort Sent copy"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="send_prepared_email_draft",
        notes="External send remains gated by exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="send_confirmed_sms_rcs",
        label="Send confirmed SMS/RCS",
        risk=RiskLevel.EXTERNAL_SEND,
        reads=("local contacts metadata", "local Messages delivery status database"),
        writes=("macOS Messages send",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="send_confirmed_sms_rcs",
        notes="Sends one SMS/RCS only after explicit current-message confirmation and verifies local delivery state.",
    ),
    CapabilityRecord(
        capability_id="run_email_triage_session",
        label="Run iCloud read-only email triage",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iCloud Mail recent message headers and bounded body excerpts",),
        writes=("data/email/triage_reports local report", "email activity state"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="run_email_triage_session",
        notes="Provider access is read-only; URLs and email addresses are redacted in chat output.",
        metadata={"provider_policy": "read_only", "default_safe_policy": "true"},
    ),
    CapabilityRecord(
        capability_id="run_unified_email_triage_session",
        label="Run unified read-only email triage",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iCloud and Seznam recent message headers and bounded body excerpts", "spam folder metadata when included"),
        writes=("data/email/triage_reports local report", "email activity state"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="run_unified_email_triage_session",
        notes="Provider access is read-only; does not open links, download attachments, send, delete, move, or mark read.",
        metadata={"provider_policy": "read_only", "default_safe_policy": "true"},
    ),
    CapabilityRecord(
        capability_id="list_recent_email_headers",
        label="List recent iCloud email headers",
        risk=RiskLevel.READ_ONLY,
        reads=("iCloud Mail recent headers",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="list_recent_email_headers",
        notes="Lists UID, date, redacted sender and subject only; never reads message bodies.",
    ),
    CapabilityRecord(
        capability_id="search_email_headers",
        label="Search recent iCloud email headers",
        risk=RiskLevel.READ_ONLY,
        reads=("iCloud Mail recent headers",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="search_email_headers",
        notes="Searches headers only within bounded scan limits; never reads message bodies.",
    ),
    CapabilityRecord(
        capability_id="list_recent_seznam_email_headers",
        label="List recent Seznam email headers",
        risk=RiskLevel.READ_ONLY,
        reads=("Seznam Mail recent headers",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="list_recent_seznam_email_headers",
        notes="Lists UID, date, redacted sender and subject only; never reads message bodies.",
    ),
    CapabilityRecord(
        capability_id="search_seznam_email_headers",
        label="Search recent Seznam email headers",
        risk=RiskLevel.READ_ONLY,
        reads=("Seznam Mail recent headers",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="search_seznam_email_headers",
        notes="Searches headers only within bounded scan limits; never reads message bodies.",
    ),
    CapabilityRecord(
        capability_id="list_unified_email_headers",
        label="List unified email headers",
        risk=RiskLevel.READ_ONLY,
        reads=("iCloud Mail recent headers", "Seznam Mail recent headers"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="list_unified_email_headers",
        notes="Merges header-only iCloud and Seznam views with source labels.",
    ),
    CapabilityRecord(
        capability_id="show_new_email_overview",
        label="Show new email overview",
        risk=RiskLevel.READ_ONLY,
        reads=("iCloud Mail recent headers", "Seznam Mail recent headers"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="show_new_email_overview",
        notes="Header-only overview plus safe next-step guidance; no bodies, links, attachments or mailbox mutations.",
    ),
    CapabilityRecord(
        capability_id="search_email_text_year",
        label="Search iCloud email body text for one year",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message body text search",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="search_email_text_year",
        notes="Requires current-message confirmation with year, terms, read-only text search consent and explicit no-link/no-send/no-delete safeguards.",
    ),
    CapabilityRecord(
        capability_id="search_seznam_email_text_year",
        label="Search Seznam email body text for one year",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed Seznam Mail message body text search",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="search_seznam_email_text_year",
        notes="Requires current-message confirmation naming Seznam, year, terms, read-only text search consent and explicit no-link/no-send/no-delete safeguards.",
    ),
    CapabilityRecord(
        capability_id="read_email_body_by_uid",
        label="Read one iCloud email body by UID",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message body by UID",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="read_email_body_by_uid",
        notes="Reads and redacts one bounded body only after UID-specific confirmation.",
    ),
    CapabilityRecord(
        capability_id="read_seznam_email_body_by_uid",
        label="Read one Seznam email body by UID",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed Seznam Mail message body by UID",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="read_seznam_email_body_by_uid",
        notes="Reads and redacts one bounded body only after UID-specific confirmation.",
    ),
    CapabilityRecord(
        capability_id="list_email_archives",
        label="List local email archives",
        risk=RiskLevel.READ_ONLY,
        reads=("local EmailArchiveVault metadata",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="list_email_archives",
        notes="Lists local archive metadata and counts without reading providers, bodies or full URLs.",
    ),
    CapabilityRecord(
        capability_id="show_email_archive_summary",
        label="Show local email archive summary",
        risk=RiskLevel.READ_ONLY,
        reads=("local EmailArchiveVault metadata", "link domains", "attachment metadata"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="show_email_archive_summary",
        notes="Shows safe archive metadata, domain counts and attachment metadata; full URLs require a separate capability.",
    ),
    CapabilityRecord(
        capability_id="show_email_archive_links",
        label="Show full links from local email archive",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed local EmailArchiveVault links.json", "full URLs from archive"),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="show_email_archive_links",
        notes="Displays full local archive links only after archive-id or UID-specific link confirmation; does not open URLs.",
    ),
    CapabilityRecord(
        capability_id="build_email_case_from_uid",
        label="Build redacted email case draft from UID",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message body by UID",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="build_email_case_from_uid",
        notes="Reads one confirmed email body and returns a redacted working case draft without saving it.",
    ),
    CapabilityRecord(
        capability_id="build_email_action_case_from_uid",
        label="Build redacted email action draft from UID",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message body by UID",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="build_email_action_case_from_uid",
        notes="Reads one confirmed email body and returns a redacted task/reminder draft without saving it.",
    ),
    CapabilityRecord(
        capability_id="build_rixo_insurance_case_from_uids",
        label="Build redacted RIXO insurance case from UIDs",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message bodies by UID",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="build_rixo_insurance_case_from_uids",
        notes="Reads 2-10 confirmed email bodies and returns one redacted insurance case draft without saving it.",
    ),
    CapabilityRecord(
        capability_id="show_email_case_links",
        label="Show full URLs from one confirmed email",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message body by UID", "full URLs extracted from the email"),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="show_email_case_links",
        notes="Displays full links only after UID-specific link confirmation; does not open URLs.",
    ),
    CapabilityRecord(
        capability_id="archive_email_by_uid",
        label="Archive one email by UID",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed iCloud Mail message by UID",),
        writes=("data/private EmailArchiveVault", "email activity state"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="archive_email_by_uid",
        notes="Provider is read-only; stores a local sensitive archive only after UID-specific confirmation.",
    ),
    CapabilityRecord(
        capability_id="save_selected_email_cases_from_uids",
        label="Save selected email cases from UIDs",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed iCloud Mail messages by UID",),
        writes=("data/private EmailCaseVault case records",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="save_selected_email_cases_from_uids",
        notes="Reads selected emails and writes local case summaries only after all UIDs are confirmed.",
    ),
    CapabilityRecord(
        capability_id="prepare_forward_email_by_uid",
        label="Prepare local email forward draft",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("source email selected by provider and UID after clear user request", "local SMTP config metadata"),
        writes=("local outbox draft",),
        requires_confirmation=False,
        confirmation_policy=ConfirmationPolicy.NONE,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_forward_email_by_uid",
        notes="Prepares a local draft from a clear user send/forward request; sending remains a separate external_send capability with exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="mark_reminder_done",
        label="Mark reminder done",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("data/reminders/reminders.json selected reminder",),
        writes=("data/reminders/reminders.json reminder status",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="mark_reminder_done",
        notes="Changes only one local reminder status after explicit id-specific confirmation.",
    ),
    CapabilityRecord(
        capability_id="list_open_reminders",
        label="List open reminders",
        risk=RiskLevel.READ_ONLY,
        reads=("data/reminders/reminders.json safe reminder summaries",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="list_open_reminders",
        notes="Lists open reminder ids, titles, due dates, priority and source type; does not read source emails or documents.",
    ),
    CapabilityRecord(
        capability_id="show_reminder_detail",
        label="Show reminder detail",
        risk=RiskLevel.READ_ONLY,
        reads=("data/reminders/reminders.json one reminder detail",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="show_reminder_detail",
        notes="Shows one safe local reminder detail with redacted links/attachments metadata; does not read source email.",
    ),
    CapabilityRecord(
        capability_id="apply_vyrazeni_leku",
        label="Soft-retire one home medicine item",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("data/lekarna/domaci_leky.csv matching active item",),
        writes=("data/lekarna/domaci_leky.csv updated item status", "CSV backup before retire"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_vyrazeni_leku",
        notes="Does not delete the row; marks exactly one active medicine item as retired after phrase confirmation.",
    ),
    CapabilityRecord(
        capability_id="search_domaci_leky",
        label="Search home medicine inventory",
        risk=RiskLevel.READ_ONLY,
        reads=("data/lekarna/domaci_leky.csv active medicine inventory",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="search_domaci_leky",
        notes="Inventory lookup only; output avoids dosing advice and warns to verify use with leaflet/pharmacist/doctor.",
    ),
    CapabilityRecord(
        capability_id="audit_domaci_lekarna",
        label="Audit home medicine inventory",
        risk=RiskLevel.READ_ONLY,
        reads=("data/lekarna/domaci_leky.csv medicine inventory",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="audit_domaci_lekarna",
        notes="Read-only inventory checklist for missing expiration, unknown location and verification flags.",
    ),
    CapabilityRecord(
        capability_id="preview_vyrazeni_leku",
        label="Preview medicine retire action",
        risk=RiskLevel.READ_ONLY,
        reads=("data/lekarna/domaci_leky.csv matching active medicine item",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="preview_vyrazeni_leku",
        notes="Preview only; actual soft-retire remains apply_vyrazeni_leku with exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="stage_lekarna_photo_import",
        label="Stage pharmacy photo import",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("selected external medicine photo files", "data/lekarna/domaci_leky.csv existing sources"),
        writes=("data/lekarna/Leky_v_Krabickach staged photo copies", "data/lekarna/photo_imports manifest CSV"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="stage_lekarna_photo_import",
        notes="Copies selected photos into private staging and writes a review manifest; final CSV/photo rename apply is separately confirmed.",
    ),
    CapabilityRecord(
        capability_id="validate_lekarna_photo_sources",
        label="Validate pharmacy photo sources",
        risk=RiskLevel.READ_ONLY,
        reads=("data/lekarna/domaci_leky.csv photo source references", "data/lekarna/Leky_v_Krabickach file existence"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="validate_lekarna_photo_sources",
        notes="Checks whether photo source files referenced from the inventory CSV exist; does not modify CSV or images.",
    ),
    CapabilityRecord(
        capability_id="apply_zmenseni_obrazku",
        label="Apply confirmed image resizing",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("selected project image files",),
        writes=("resized image files", "data/media/image_resize_backups original copies"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="apply_zmenseni_obrazku",
        notes="Overwrites only selected in-project images after creating backups and explicit phrase confirmation.",
    ),
    CapabilityRecord(
        capability_id="preview_zmenseni_obrazku",
        label="Preview image resizing",
        risk=RiskLevel.READ_ONLY,
        reads=("selected project image file metadata", "image sizes"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="preview_zmenseni_obrazku",
        notes="Preview only; apply_zmenseni_obrazku remains the confirmed overwrite step with backups.",
    ),
    CapabilityRecord(
        capability_id="prepare_human_adam_image_candidate",
        label="Prepare a private Human–Adam image candidate",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("one explicit Human–Adam chat request",),
        writes=("private Human–Adam image candidate metadata",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="app.communication.human_adam_images.HumanAdamImageCandidateStore.prepare",
        notes="Prepares only a private prompt and parameter preview; it does not call a paid API.",
    ),
    CapabilityRecord(
        capability_id="generate_human_adam_image_candidate",
        label="Generate one Human–Adam image candidate under durable consent",
        risk=RiskLevel.EXTERNAL_GENERATION,
        reads=("one reviewed prompt and allowlisted image parameters",),
        writes=("one versioned private Human–Adam image candidate",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="app.communication.human_adam_images.HumanAdamImageCandidateStore.generate",
        notes="Calls the image API only when global durable consent is active and the prompt is public, fictional or non-sensitive; never publishes the result.",
        metadata={"durable_consent": "trusted_external_generation_v1"},
    ),
    CapabilityRecord(
        capability_id="generate_project_audio_asset",
        label="Generate a project audio asset under durable consent",
        risk=RiskLevel.EXTERNAL_GENERATION,
        reads=("public, fictional or non-sensitive project text", "registered voice selection"),
        writes=("generated audio asset in the active project",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="app.speech.edge_tts_mp3.synthesize_edge_tts_mp3_sync",
        notes="Generates MP3 bytes only while global durable consent is active; the active development step may save them to its project but never publishes them.",
        metadata={"durable_consent": "trusted_external_generation_v1"},
    ),
    CapabilityRecord(
        capability_id="review_human_adam_image_candidate",
        label="Approve or reject one Human–Adam image candidate",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("one generated private Human–Adam image candidate",),
        writes=("private approval or rejection state for the same candidate version",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="app.communication.human_adam_images.HumanAdamImageCandidateStore.decide",
        notes="The explicit UI decision changes only candidate state; it never publishes, overwrites, or inserts a file.",
    ),
    CapabilityRecord(
        capability_id="apply_lekarna_photo_import",
        label="Apply reviewed pharmacy photo import",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("reviewed pharmacy photo import manifest", "medicine photo files", "data/lekarna/domaci_leky.csv"),
        writes=("renamed medicine photo files", "data/lekarna/domaci_leky.csv appended rows", "photo import report and CSV backup"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_lekarna_photo_import",
        notes="Applies only included manifest rows; new items remain marked for verification.",
    ),
    CapabilityRecord(
        capability_id="save_email_action_case_reminder",
        label="Save email action reminder",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed safe email action fields",),
        writes=("data/reminders/reminders.json reminder draft",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="save_email_action_case_reminder",
        notes="Writes a safe reminder draft only after id-specific confirmation; does not reread email.",
    ),
    CapabilityRecord(
        capability_id="save_payment_case_document",
        label="Save payment case document",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed local invoice/document file",),
        writes=("data/private/payment_cases document copy", "payment case document manifest"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="save_payment_case_document",
        notes="Copies a confirmed local file into the private payment case archive.",
    ),
    CapabilityRecord(
        capability_id="save_payment_sms_reminder",
        label="Save payment SMS reminder",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed payment SMS text", "verified due date fields"),
        writes=("data/reminders/reminders.json payment reminder",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="save_payment_sms_reminder",
        notes="Stores only a safe reminder; full SMS URLs/tokens are not stored.",
    ),
    CapabilityRecord(
        capability_id="inspect_payment_page_for_reminder",
        label="Inspect confirmed payment page for reminder fields",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed HTTPS payment page", "safe payment reminder fields"),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="inspect_payment_page_for_reminder",
        notes="Fetches only after domain-specific confirmation and redacts full URLs/tokens from output.",
    ),
    CapabilityRecord(
        capability_id="save_document_due_reminder",
        label="Save document due-date reminder",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed private document due-date candidate",),
        writes=("data/reminders/reminders.json document reminder",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="save_document_due_reminder",
        notes="Creates a reminder from a confirmed due-date candidate; does not expose document text.",
    ),
    CapabilityRecord(
        capability_id="apply_document_import",
        label="Import confirmed document into private vault",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed local document file", "document text for metadata extraction"),
        writes=("data/private/documents vault copy", "document manifest and search index"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_document_import",
        notes="Copies a confirmed local document into the private vault and indexes safe metadata.",
    ),
    CapabilityRecord(
        capability_id="prepare_document_import",
        label="Preview private document import",
        risk=RiskLevel.READ_ONLY,
        reads=("selected local document metadata", "bounded extracted document text for metadata proposal"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_document_import",
        notes="Preview only; final vault copy remains a separate confirmed apply_document_import capability.",
    ),
    CapabilityRecord(
        capability_id="prepare_restricted_bank_document_import",
        label="Preview restricted bank document import",
        risk=RiskLevel.READ_ONLY,
        reads=("selected local bank document", "bank identifiers for masked metadata preview"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_restricted_bank_document_import",
        notes="Preview masks account and IBAN values and never persists raw OCR text.",
    ),
    CapabilityRecord(
        capability_id="apply_restricted_bank_document_import",
        label="Import bank document with restricted metadata",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed local bank document", "bank identifiers for restricted metadata"),
        writes=(
            "data/private/documents vault copy",
            "restricted bank metadata",
            "redacted document search index",
        ),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_restricted_bank_document_import",
        notes="Stores full account identifiers only in restricted metadata; raw OCR is excluded from search.",
    ),
    CapabilityRecord(
        capability_id="scan_document_inbox",
        label="Scan private document inbox",
        risk=RiskLevel.READ_ONLY,
        reads=("data/private/documents/inbox/incoming file metadata",),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="scan_document_inbox",
        notes="Lists waiting private inbox files by name, size and modified time; does not move, index or read full content.",
    ),
    CapabilityRecord(
        capability_id="scan_downloaded_pdfs",
        label="Scan Downloads PDFs for ScanDocu",
        risk=RiskLevel.READ_ONLY,
        reads=("top-level Downloads PDF metadata", "ScanDocu candidate status metadata"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="scan_downloaded_pdfs",
        notes="Lists recent PDF candidates only; prepare_next_scandocu_document is the separate local-write preparation step.",
    ),
    CapabilityRecord(
        capability_id="preview_document_reindex",
        label="Preview private document reindex",
        risk=RiskLevel.READ_ONLY,
        reads=("private document manifests", "private document index"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="preview_document_reindex",
        notes="Shows proposed metadata changes only; apply_document_reindex remains confirmed local write.",
    ),
    CapabilityRecord(
        capability_id="scan_mobile_document_inbox",
        label="Scan mobile document inbox",
        risk=RiskLevel.READ_ONLY,
        reads=("iPhone Shortcuts document capture manifests and file metadata", "process_request.json existence"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="scan_mobile_document_inbox",
        notes="Lists mobile capture batches and page filenames; does not process images, create PDFs, move or delete files.",
    ),
    CapabilityRecord(
        capability_id="document_vault_status",
        label="Show private document vault status",
        risk=RiskLevel.READ_ONLY,
        reads=("private document index aggregates", "private document inbox counts", "document due-date candidate counts"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="document_vault_status",
        notes="Aggregated status only; does not expose full document text or modify the vault.",
    ),
    CapabilityRecord(
        capability_id="search_private_documents",
        label="Search private document vault",
        risk=RiskLevel.READ_ONLY,
        reads=("private document search index", "private document metadata", "short redacted snippets"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="search_private_documents",
        notes="Returns metadata and short snippets only; full document operations remain separate confirmed capabilities.",
    ),
    CapabilityRecord(
        capability_id="inspect_document_text",
        label="Inspect private document text and due-date signals",
        risk=RiskLevel.READ_ONLY,
        reads=("selected local or vaulted document text", "due-date candidates"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="inspect_document_text",
        notes="Returns redacted document inspection snippets; does not modify the vault.",
    ),
    CapabilityRecord(
        capability_id="apply_document_reindex",
        label="Apply private document metadata reindex",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("private document manifests", "private document index"),
        writes=("private document manifests", "private document index", "reindex backup and run log"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_document_reindex",
        notes="Updates only private document metadata after explicit reindex confirmation; PDFs are not changed.",
    ),
    CapabilityRecord(
        capability_id="process_mobile_document_inbox",
        label="Process mobile document inbox",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iPhone document inbox manifests and images", "process_request.json"),
        writes=("private working PDFs", "mobile processing manifests", "mobile process run log"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="process_mobile_document_inbox",
        notes="Prepares working PDFs/OCR metadata from an explicit mobile request; final vault import is separate.",
    ),
    CapabilityRecord(
        capability_id="prepare_mobile_document_batch",
        label="Prepare one mobile document batch as working PDF",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iPhone document inbox manifest and page images",),
        writes=("private mobile processing working PDF", "processing manifest", "mobile batch run log"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_mobile_document_batch",
        notes="Creates working copies only; final vault import remains separate and confirmed.",
    ),
    CapabilityRecord(
        capability_id="prepare_next_scandocu_document",
        label="Prepare next Downloads PDF for ScanDocu review",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("newest unprocessed Downloads PDF metadata and text extraction",),
        writes=("private ScanDocu processing copy", "ScanDocu candidate metadata", "candidate index log"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_next_scandocu_document",
        notes="Creates a private review candidate; final document import/review action is separate.",
    ),
    CapabilityRecord(
        capability_id="prepare_mobile_document_final_import",
        label="Preview final mobile document import",
        risk=RiskLevel.READ_ONLY,
        reads=("processed mobile document manifest", "proposed final import metadata"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_mobile_document_final_import",
        notes="Preview only; final import remains apply_mobile_document_final_import with exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="apply_mobile_document_final_import",
        label="Import processed mobile document into private vault",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("processed mobile document PDF", "mobile document analysis metadata"),
        writes=("data/private/documents vault copy", "document manifest and search index", "mobile import marker"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_mobile_document_final_import",
        notes="Final import of one processed mobile document after explicit filename/domain confirmation.",
    ),
    CapabilityRecord(
        capability_id="run_document_print_job",
        label="Run prepared private document print job",
        risk=RiskLevel.SYSTEM_CHANGE,
        reads=("private document print_queue job",),
        writes=("system print queue", "private print job status log"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="run_document_print_job",
        notes="Runs macOS lp for a prepared print_queue copy after explicit print-job confirmation.",
    ),
    CapabilityRecord(
        capability_id="prepare_document_print_job",
        label="Prepare private document print queue copy",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("selected private document vault file",),
        writes=("private print_queue copy", "print job status log"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_document_print_job",
        notes="Only prepares a print_queue copy; actual printing remains run_document_print_job with exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="resolve_document_inbox_item",
        label="Resolve private document inbox item",
        risk=RiskLevel.DESTRUCTIVE,
        reads=("private document inbox file", "private document index duplicate state"),
        writes=("move to processed folder or delete inbox file",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="resolve_document_inbox_item",
        notes="Can move or delete an inbox file; delete path needs especially explicit confirmation.",
    ),
    CapabilityRecord(
        capability_id="propose_document_inbox_cleanup",
        label="Propose private document inbox cleanup action",
        risk=RiskLevel.READ_ONLY,
        reads=("private document inbox item", "duplicate/import status metadata"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="propose_document_inbox_cleanup",
        notes="Proposal only; move/delete remains resolve_document_inbox_item with exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="prepare_lekarna_photo_import",
        label="Prepare pharmacy photo import manifest",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("data/lekarna/Leky_v_Krabickach photo filenames", "data/lekarna/domaci_leky.csv existing sources"),
        writes=("data/lekarna/photo_imports manifest CSV",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_lekarna_photo_import",
        notes="Writes only a review manifest template; actual CSV/photo changes remain apply_lekarna_photo_import with confirmation.",
    ),
)


def all_capabilities() -> tuple[CapabilityRecord, ...]:
    return CAPABILITIES


def capability_map() -> dict[str, CapabilityRecord]:
    return {item.capability_id: item for item in CAPABILITIES}


def get_capability(capability_id: str) -> CapabilityRecord:
    normalized = capability_id.strip()
    try:
        return capability_map()[normalized]
    except KeyError as exc:
        raise KeyError(f"unknown capability_id: {capability_id!r}") from exc


def validate_registry(records: tuple[CapabilityRecord, ...] = CAPABILITIES) -> tuple[str, ...]:
    errors: list[str] = []
    seen: set[str] = set()
    for record in records:
        if record.capability_id in seen:
            errors.append(f"duplicate capability_id: {record.capability_id}")
        seen.add(record.capability_id)
        if record.capability_id == "git_push_main_after_guard":
            if record.risk != RiskLevel.GIT_PUBLISH:
                errors.append("git_push_main_after_guard must use git_publish risk")
            if record.metadata.get("requires_green_guard") != "true":
                errors.append("git_push_main_after_guard must require a green guard")
        if record.risk == RiskLevel.EXTERNAL_SEND:
            if record.confirmation_policy != ConfirmationPolicy.EXACT_CURRENT_MESSAGE:
                errors.append(f"{record.capability_id} external_send must use exact_current_message")
            if record.audit == AuditPolicy.FULL_LOCAL:
                errors.append(f"{record.capability_id} external_send cannot use full_local audit")
        if record.risk == RiskLevel.EXTERNAL_GENERATION:
            if record.requires_confirmation:
                errors.append(f"{record.capability_id} external_generation cannot use per-action confirmation")
            if record.metadata.get("durable_consent") != "trusted_external_generation_v1":
                errors.append(f"{record.capability_id} external_generation needs durable consent metadata")
    return tuple(errors)
