from __future__ import annotations

from app.capabilities.models import (
    AuditPolicy,
    CapabilityRecord,
    ConfirmationPolicy,
    MobilePolicy,
    RiskLevel,
    VoicePolicy,
)


CAPABILITIES: tuple[CapabilityRecord, ...] = (
    CapabilityRecord(
        capability_id="git_safety_check",
        label="Git staged safety check",
        risk=RiskLevel.READ_ONLY,
        reads=(
            "git staged file list",
            "branch guard state",
            "memory/infrastructure/git_branch_archive.md",
        ),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="scripts/git_safety_check.py",
        notes="Checks staged content and branch risk before commit.",
    ),
    CapabilityRecord(
        capability_id="work_context_guard",
        label="Work context guard",
        risk=RiskLevel.READ_ONLY,
        reads=(
            "git status",
            "branch guard state",
            "merge/rebase/cherry-pick/revert markers",
        ),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="scripts/work_context_guard.py",
        notes="Read-only guard before switching topics or starting a new session.",
    ),
    CapabilityRecord(
        capability_id="git_push_main_after_guard",
        label="Routine push to origin main after green guard",
        risk=RiskLevel.GIT_PUBLISH,
        reads=(
            "git branch and upstream state",
            "git working tree state",
            "last commit file list",
        ),
        writes=("git push origin main",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="scripts/git_push_guard.py + git push origin main",
        notes="Allowed without another question only after git_push_guard.py reports routine push allowed.",
        metadata={"requires_green_guard": "true", "allowed_remote": "origin", "allowed_branch": "main"},
    ),
    CapabilityRecord(
        capability_id="copy_downloads_files_to_knowledge_inbox",
        label="Copy selected Downloads files to private knowledge inbox",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("selected top-level Downloads files metadata and bytes",),
        writes=("data/private/knowledge_inbox/incoming copied files",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="copy_downloads_files_to_knowledge_inbox",
        notes="Copies only explicitly selected relative files from Downloads; does not read content for summarization.",
    ),
    CapabilityRecord(
        capability_id="prepare_iphone_shortcut",
        label="Prepare private iPhone Shortcut request draft",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("shortcut name, purpose and details from current request",),
        writes=("data/private/iphone_shortcuts/requests markdown draft",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="prepare_iphone_shortcut",
        notes="Without confirmation returns only a preview prompt; confirmed path writes a private request draft, not a shortcut file.",
    ),
    CapabilityRecord(
        capability_id="quick_notes_action_status",
        label="Quick Notes action inbox",
        risk=RiskLevel.READ_ONLY,
        reads=(
            "data/private/quick_notes metadata",
            "selected quick note text summaries",
        ),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="quick_notes_action_status",
        notes="Read-only overview for choosing later confirmed actions.",
    ),
    CapabilityRecord(
        capability_id="restore_path_from_backup",
        label="Restore one PythonMF path from backup",
        risk=RiskLevel.DESTRUCTIVE,
        reads=("selected Samantha backup snapshot", "target path metadata"),
        writes=("restored PythonMF file or folder", ".before_restore copy of previous target"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="restore_path_from_backup",
        notes="Restores only a safe relative path after preview; sensitive paths require extra recovery wording.",
    ),
    CapabilityRecord(
        capability_id="run_workflow_command",
        label="Run registered local workflow command",
        risk=RiskLevel.SYSTEM_CHANGE,
        reads=("workflow command registry", "pending workflow confirmation card"),
        writes=("registered command side effects", "workflow pending-command state"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="run_workflow_command",
        notes="Runs only registered argv commands; commands marked as requiring confirmation need a current-message confirmation.",
    ),
    CapabilityRecord(
        capability_id="send_prepared_email_draft",
        label="Send prepared email draft",
        risk=RiskLevel.EXTERNAL_SEND,
        reads=("local outbox draft",),
        writes=("SMTP send", "best-effort Sent copy"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="send_prepared_email_draft",
        notes="External send remains gated by exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="send_confirmed_sms_rcs",
        label="Send confirmed SMS/RCS",
        risk=RiskLevel.EXTERNAL_SEND,
        reads=("local contacts metadata", "local Messages delivery status database"),
        writes=("macOS Messages send",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="send_confirmed_sms_rcs",
        notes="Sends one SMS/RCS only after explicit current-message confirmation and verifies local delivery state.",
    ),
    CapabilityRecord(
        capability_id="run_email_triage_session",
        label="Run iCloud read-only email triage",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iCloud Mail recent message headers and bounded body excerpts",),
        writes=("data/email/triage_reports local report", "email activity state"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="run_email_triage_session",
        notes="Provider access is read-only; URLs and email addresses are redacted in chat output.",
        metadata={"provider_policy": "read_only", "default_safe_policy": "true"},
    ),
    CapabilityRecord(
        capability_id="run_unified_email_triage_session",
        label="Run unified read-only email triage",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iCloud and Seznam recent message headers and bounded body excerpts", "spam folder metadata when included"),
        writes=("data/email/triage_reports local report", "email activity state"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="run_unified_email_triage_session",
        notes="Provider access is read-only; does not open links, download attachments, send, delete, move, or mark read.",
        metadata={"provider_policy": "read_only", "default_safe_policy": "true"},
    ),
    CapabilityRecord(
        capability_id="build_email_case_from_uid",
        label="Build redacted email case draft from UID",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message body by UID",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="build_email_case_from_uid",
        notes="Reads one confirmed email body and returns a redacted working case draft without saving it.",
    ),
    CapabilityRecord(
        capability_id="build_email_action_case_from_uid",
        label="Build redacted email action draft from UID",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message body by UID",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="build_email_action_case_from_uid",
        notes="Reads one confirmed email body and returns a redacted task/reminder draft without saving it.",
    ),
    CapabilityRecord(
        capability_id="build_rixo_insurance_case_from_uids",
        label="Build redacted RIXO insurance case from UIDs",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message bodies by UID",),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="build_rixo_insurance_case_from_uids",
        notes="Reads 2-10 confirmed email bodies and returns one redacted insurance case draft without saving it.",
    ),
    CapabilityRecord(
        capability_id="show_email_case_links",
        label="Show full URLs from one confirmed email",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed iCloud Mail message body by UID", "full URLs extracted from the email"),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="show_email_case_links",
        notes="Displays full links only after UID-specific link confirmation; does not open URLs.",
    ),
    CapabilityRecord(
        capability_id="archive_email_by_uid",
        label="Archive one email by UID",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed iCloud Mail message by UID",),
        writes=("data/private EmailArchiveVault", "email activity state"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="archive_email_by_uid",
        notes="Provider is read-only; stores a local sensitive archive only after UID-specific confirmation.",
    ),
    CapabilityRecord(
        capability_id="save_selected_email_cases_from_uids",
        label="Save selected email cases from UIDs",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed iCloud Mail messages by UID",),
        writes=("data/private EmailCaseVault case records",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="save_selected_email_cases_from_uids",
        notes="Reads selected emails and writes local case summaries only after all UIDs are confirmed.",
    ),
    CapabilityRecord(
        capability_id="prepare_forward_email_by_uid",
        label="Prepare local email forward draft",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed source email by provider and UID", "local SMTP config metadata"),
        writes=("local outbox draft",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="prepare_forward_email_by_uid",
        notes="Prepares a local draft only; sending remains a separate external_send capability.",
    ),
    CapabilityRecord(
        capability_id="mark_reminder_done",
        label="Mark reminder done",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("data/reminders/reminders.json selected reminder",),
        writes=("data/reminders/reminders.json reminder status",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="mark_reminder_done",
        notes="Changes only one local reminder status after explicit id-specific confirmation.",
    ),
    CapabilityRecord(
        capability_id="apply_vyrazeni_leku",
        label="Soft-retire one home medicine item",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("data/lekarna/domaci_leky.csv matching active item",),
        writes=("data/lekarna/domaci_leky.csv updated item status", "CSV backup before retire"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_vyrazeni_leku",
        notes="Does not delete the row; marks exactly one active medicine item as retired after phrase confirmation.",
    ),
    CapabilityRecord(
        capability_id="apply_zmenseni_obrazku",
        label="Apply confirmed image resizing",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("selected project image files",),
        writes=("resized image files", "data/media/image_resize_backups original copies"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="apply_zmenseni_obrazku",
        notes="Overwrites only selected in-project images after creating backups and explicit phrase confirmation.",
    ),
    CapabilityRecord(
        capability_id="apply_lekarna_photo_import",
        label="Apply reviewed pharmacy photo import",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("reviewed pharmacy photo import manifest", "medicine photo files", "data/lekarna/domaci_leky.csv"),
        writes=("renamed medicine photo files", "data/lekarna/domaci_leky.csv appended rows", "photo import report and CSV backup"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_lekarna_photo_import",
        notes="Applies only included manifest rows; new items remain marked for verification.",
    ),
    CapabilityRecord(
        capability_id="save_email_action_case_reminder",
        label="Save email action reminder",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed safe email action fields",),
        writes=("data/reminders/reminders.json reminder draft",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="save_email_action_case_reminder",
        notes="Writes a safe reminder draft only after id-specific confirmation; does not reread email.",
    ),
    CapabilityRecord(
        capability_id="save_payment_case_document",
        label="Save payment case document",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed local invoice/document file",),
        writes=("data/private/payment_cases document copy", "payment case document manifest"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="save_payment_case_document",
        notes="Copies a confirmed local file into the private payment case archive.",
    ),
    CapabilityRecord(
        capability_id="save_payment_sms_reminder",
        label="Save payment SMS reminder",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed payment SMS text", "verified due date fields"),
        writes=("data/reminders/reminders.json payment reminder",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="save_payment_sms_reminder",
        notes="Stores only a safe reminder; full SMS URLs/tokens are not stored.",
    ),
    CapabilityRecord(
        capability_id="inspect_payment_page_for_reminder",
        label="Inspect confirmed payment page for reminder fields",
        risk=RiskLevel.PRIVATE_EXPORT,
        reads=("confirmed HTTPS payment page", "safe payment reminder fields"),
        writes=(),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="inspect_payment_page_for_reminder",
        notes="Fetches only after domain-specific confirmation and redacts full URLs/tokens from output.",
    ),
    CapabilityRecord(
        capability_id="save_document_due_reminder",
        label="Save document due-date reminder",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed private document due-date candidate",),
        writes=("data/reminders/reminders.json document reminder",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.SAFE_SUMMARY,
        tool="save_document_due_reminder",
        notes="Creates a reminder from a confirmed due-date candidate; does not expose document text.",
    ),
    CapabilityRecord(
        capability_id="apply_document_import",
        label="Import confirmed document into private vault",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("confirmed local document file", "document text for metadata extraction"),
        writes=("data/private/documents vault copy", "document manifest and search index"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_document_import",
        notes="Copies a confirmed local document into the private vault and indexes safe metadata.",
    ),
    CapabilityRecord(
        capability_id="prepare_document_import",
        label="Preview private document import",
        risk=RiskLevel.READ_ONLY,
        reads=("selected local document metadata", "bounded extracted document text for metadata proposal"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_document_import",
        notes="Preview only; final vault copy remains a separate confirmed apply_document_import capability.",
    ),
    CapabilityRecord(
        capability_id="inspect_document_text",
        label="Inspect private document text and due-date signals",
        risk=RiskLevel.READ_ONLY,
        reads=("selected local or vaulted document text", "due-date candidates"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="inspect_document_text",
        notes="Returns redacted document inspection snippets; does not modify the vault.",
    ),
    CapabilityRecord(
        capability_id="apply_document_reindex",
        label="Apply private document metadata reindex",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("private document manifests", "private document index"),
        writes=("private document manifests", "private document index", "reindex backup and run log"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_document_reindex",
        notes="Updates only private document metadata after explicit reindex confirmation; PDFs are not changed.",
    ),
    CapabilityRecord(
        capability_id="process_mobile_document_inbox",
        label="Process mobile document inbox",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iPhone document inbox manifests and images", "process_request.json"),
        writes=("private working PDFs", "mobile processing manifests", "mobile process run log"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="process_mobile_document_inbox",
        notes="Prepares working PDFs/OCR metadata from an explicit mobile request; final vault import is separate.",
    ),
    CapabilityRecord(
        capability_id="prepare_mobile_document_batch",
        label="Prepare one mobile document batch as working PDF",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("iPhone document inbox manifest and page images",),
        writes=("private mobile processing working PDF", "processing manifest", "mobile batch run log"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_mobile_document_batch",
        notes="Creates working copies only; final vault import remains separate and confirmed.",
    ),
    CapabilityRecord(
        capability_id="prepare_next_scandocu_document",
        label="Prepare next Downloads PDF for ScanDocu review",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("newest unprocessed Downloads PDF metadata and text extraction",),
        writes=("private ScanDocu processing copy", "ScanDocu candidate metadata", "candidate index log"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_next_scandocu_document",
        notes="Creates a private review candidate; final document import/review action is separate.",
    ),
    CapabilityRecord(
        capability_id="prepare_mobile_document_final_import",
        label="Preview final mobile document import",
        risk=RiskLevel.READ_ONLY,
        reads=("processed mobile document manifest", "proposed final import metadata"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_mobile_document_final_import",
        notes="Preview only; final import remains apply_mobile_document_final_import with exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="apply_mobile_document_final_import",
        label="Import processed mobile document into private vault",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("processed mobile document PDF", "mobile document analysis metadata"),
        writes=("data/private/documents vault copy", "document manifest and search index", "mobile import marker"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="apply_mobile_document_final_import",
        notes="Final import of one processed mobile document after explicit filename/domain confirmation.",
    ),
    CapabilityRecord(
        capability_id="run_document_print_job",
        label="Run prepared private document print job",
        risk=RiskLevel.SYSTEM_CHANGE,
        reads=("private document print_queue job",),
        writes=("system print queue", "private print job status log"),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="run_document_print_job",
        notes="Runs macOS lp for a prepared print_queue copy after explicit print-job confirmation.",
    ),
    CapabilityRecord(
        capability_id="prepare_document_print_job",
        label="Prepare private document print queue copy",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("selected private document vault file",),
        writes=("private print_queue copy", "print job status log"),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_document_print_job",
        notes="Only prepares a print_queue copy; actual printing remains run_document_print_job with exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="resolve_document_inbox_item",
        label="Resolve private document inbox item",
        risk=RiskLevel.DESTRUCTIVE,
        reads=("private document inbox file", "private document index duplicate state"),
        writes=("move to processed folder or delete inbox file",),
        requires_confirmation=True,
        confirmation_policy=ConfirmationPolicy.EXACT_CURRENT_MESSAGE,
        voice_allowed=VoicePolicy.APPROVAL_ONLY,
        mobile_allowed=MobilePolicy.APPROVAL_CARD,
        audit=AuditPolicy.REDACTED,
        tool="resolve_document_inbox_item",
        notes="Can move or delete an inbox file; delete path needs especially explicit confirmation.",
    ),
    CapabilityRecord(
        capability_id="propose_document_inbox_cleanup",
        label="Propose private document inbox cleanup action",
        risk=RiskLevel.READ_ONLY,
        reads=("private document inbox item", "duplicate/import status metadata"),
        writes=(),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="propose_document_inbox_cleanup",
        notes="Proposal only; move/delete remains resolve_document_inbox_item with exact confirmation.",
    ),
    CapabilityRecord(
        capability_id="prepare_lekarna_photo_import",
        label="Prepare pharmacy photo import manifest",
        risk=RiskLevel.LOCAL_WRITE,
        reads=("data/lekarna/Leky_v_Krabickach photo filenames", "data/lekarna/domaci_leky.csv existing sources"),
        writes=("data/lekarna/photo_imports manifest CSV",),
        requires_confirmation=False,
        voice_allowed=VoicePolicy.ALLOWED,
        mobile_allowed=MobilePolicy.ALLOWED,
        audit=AuditPolicy.REDACTED,
        tool="prepare_lekarna_photo_import",
        notes="Writes only a review manifest template; actual CSV/photo changes remain apply_lekarna_photo_import with confirmation.",
    ),
)


def all_capabilities() -> tuple[CapabilityRecord, ...]:
    return CAPABILITIES


def capability_map() -> dict[str, CapabilityRecord]:
    return {item.capability_id: item for item in CAPABILITIES}


def get_capability(capability_id: str) -> CapabilityRecord:
    normalized = capability_id.strip()
    try:
        return capability_map()[normalized]
    except KeyError as exc:
        raise KeyError(f"unknown capability_id: {capability_id!r}") from exc


def validate_registry(records: tuple[CapabilityRecord, ...] = CAPABILITIES) -> tuple[str, ...]:
    errors: list[str] = []
    seen: set[str] = set()
    for record in records:
        if record.capability_id in seen:
            errors.append(f"duplicate capability_id: {record.capability_id}")
        seen.add(record.capability_id)
        if record.capability_id == "git_push_main_after_guard":
            if record.risk != RiskLevel.GIT_PUBLISH:
                errors.append("git_push_main_after_guard must use git_publish risk")
            if record.metadata.get("requires_green_guard") != "true":
                errors.append("git_push_main_after_guard must require a green guard")
        if record.risk == RiskLevel.EXTERNAL_SEND:
            if record.confirmation_policy != ConfirmationPolicy.EXACT_CURRENT_MESSAGE:
                errors.append(f"{record.capability_id} external_send must use exact_current_message")
            if record.audit == AuditPolicy.FULL_LOCAL:
                errors.append(f"{record.capability_id} external_send cannot use full_local audit")
    return tuple(errors)
